kind: Service
apiVersion: v1
metadata:
  name: elasticsearch-discovery
spec:
  selector:
    app: elasticsearch
    role: discovery
  clusterIP: None
  ports:
  - protocol: TCP
    port: 9300
    targetPort: 9300
